### PR TITLE
Upstream deps

### PR DESCRIPTION
**Pull request by He-Pin**
1. update dependencies
2. import language features

### CODE REVIEW

**Comment by He-Pin** [comment]
Once this gets merged I will merge back to the translation repo.
@fommil I think we could set up the CI too.

**Comment by fommil** [comment]
hi, thanks for doing this, but I'm not interested in updating the book or reference material now that the book is in print. Feel free to upgrade the software in the Chinese translation.

**Comment by He-Pin** [comment]
@fommil Thanks :)

**Comment by He-Pin** [comment]
One day scalaz 7.3 is out , then that should be a good time.

**Pull request closed without merging**
